export const GET_BOOKS = "GET_BOOKS";
export const GET_PAGINATED_BOOKS = "GET_PAGINATED_BOOKS";
export const GET_QUERIED_BOOKS = "GET_QUERIED_BOOKS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_ERROR = "GET_BOOKS_ERROR";


