export const types = {
  GET_BOOKS: "GET_BOOKS",
  GET_PAGINATED_BOOKS: "GET_PAGINATED_BOOKS",
  GET_QUERIED_BOOKS: "GET_QUERIED_BOOKS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SET_BOOKS_SUCCESS: "SET_BOOKS_SUCCESS",
  SET_BOOKS_ERROR: "SET_BOOKS_ERROR",
};
